package com.example.demo.mock;

import com.example.demo.user.domain.User;
import com.example.demo.user.domain.UserStatus;
import com.example.demo.user.service.port.UserRepository;

import java.util.Optional;
import java.util.concurrent.atomic.AtomicInteger;

public class FakeUserRepository implements UserRepository {

    private final AtomicInteger autoGeneratedId = new AtomicInteger(0);

    @Override
    public Optional<User> findByIdAndStatus(long id, UserStatus userStatus) {
        return Optional.empty();
    }

    @Override
    public Optional<User> findByEmailAndStatus(String email, UserStatus userStatus) {
        return Optional.empty();
    }

    @Override
    public User save(User user) {
        return null;
    }

    @Override
    public Optional<User> findById(long id) {
        return Optional.empty();
    }
}
